import { Button, CssBaseline, ThemeProvider } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import MatchList from '../components/MatchList'
import SettingsMenu from '../components/SettingsMenu'
import useStore from '../global/state'
import styles from '../styles/Home.module.css'
import { darkTheme, lightTheme } from '../styles/themes'

const Captions: NextPage = () => {
  const store = useStore();
  const [isLight, setIsLight] = useState(true); //default is darkmode


  //run on store.isLight update
  useEffect(() => {
    setIsLight(store.isLight);
  }, [store.isLight]);

  return (
    <ThemeProvider theme={isLight ? lightTheme : darkTheme}>
      <CssBaseline/>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <SettingsMenu/>
          <h2 className={styles.title} style={{marginBottom:'4rem'}}>Captions</h2>
          <MatchList/>
        </main>
      </div>
    </ThemeProvider>
  )
}

export default Captions
