import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import useStore from '../global/state'
import {useEffect, useState} from 'react'
import { ThemeProvider, CssBaseline, Button } from '@mui/material'
import {darkTheme, lightTheme} from '../styles/themes'
import SettingsMenu from '../components/SettingsMenu'
import LoginForm from '../components/LoginForm'
import { useSession } from 'next-auth/react'

const Captions: NextPage = () => {
  const store = useStore();
  const [isLight, setIsLight] = useState(true); //default is darkmode
  const {data: session} = useSession();
  console.log(session);

  //run on store.isLight update
  useEffect(() => {
    setIsLight(store.isLight);
  }, [store.isLight]);

  const captionId = 'AUieDaaWBOuVpqfFqAR5tIfxeuJxm2kUINdpolr6vNaB6D7aE8c';

  useEffect(() => {
    getCaptionId('something');

  }, [])

  useEffect(() => {
    getCaptions(captionId);

  }, [session])




  async function getCaptions(captionId:string){
    // const url = 'https://www.googleapis.com/youtube/v3/captions/?videoId=' + vidId + '&key=' + process.env.NEXT_PUBLIC_API_KEY + '&part=snippet';  
    const url = 'https://www.googleapis.com/youtube/v3/captions/'+captionId +'?&access_token='+session?.token.access_token;
    const res = await fetch(url)
    .then(res => res.json())
    .then(data => console.log(data))
    // .then(data => console.log( data.items[0]))
    .catch(err => console.log(err));

  }

  async function getCaptionId(urlInput:string){
    // const vidId = youtube_parser(urlInput);
    // const vidId = 'jE6hIXyg39E&t=977s';
    const vidId = 'KHYOq8iSZic';

    // const url = 'https://www.googleapis.com/youtube/v3/videos?id=' + vidId + '&key=' + process.env.NEXT_PUBLIC_API_KEY + '&part=snippet';  
    const url = 'https://www.googleapis.com/youtube/v3/captions?videoId=' + vidId + '&key=' + process.env.NEXT_PUBLIC_API_KEY + '&part=snippet';  
                       // const url = 'https://www.googleapis.com/youtube/v3/videos?id=XxfkIwoj2aM&ab_&key=API_KEY_HERE&part=snippet'
    const res = await fetch(url)
    .then(res => res.json())
    .then(data => console.log(data.items[0].id))
    // .then(data => console.log( data.items[0]))
    .catch(err => console.log(err));
  }



  return (
    <ThemeProvider theme={isLight ? lightTheme : darkTheme}>
      <CssBaseline/>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <SettingsMenu/>
          <h2 className={styles.title}>Captions</h2>
          <p>Please enter a url to get started.</p>
          <LoginForm/>
        </main>
      </div>
    </ThemeProvider>
  )
}

export default Captions
