import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import useStore from '../global/state'
import {useEffect, useState} from 'react'
import { ThemeProvider, CssBaseline, Button } from '@mui/material'
import {darkTheme, lightTheme} from '../styles/themes'
import SettingsMenu from '../components/SettingsMenu'
import {DownloadedClip, TimestampObject} from '../global/types'
import CutVideoCard from '../components/Download/CutVideoCard'
import RotateRightIcon from '@mui/icons-material/RotateRight';
import { compress, decompress } from '@amoutonbrady/lz-string'

const Download: NextPage = () => {
  const store = useStore();
  const [isLight, setIsLight] = useState(true); //default is darkmode
  const [downloadedVids, setDownloadedVids] = useState<DownloadedClip[]>([]) //for local use - user must be able to see both included/removed clips in case they change their mind
  const [areVidsDownloaded, setAreVidsDownloaded] = useState(false)

  //run on store.isLight update
  useEffect(() => {
    setIsLight(store.isLight);
  }, [store.isLight]);

  useEffect(() => {
    if(!areVidsDownloaded)
      downloadVids()
  }, [])

  const downloadVids = async() => {
    for(let i = 0; i < store.downloadQueue.length; i++){
      await callToApi(store.downloadQueue[i].url, i, store.downloadQueue[i].timestampData)
    }
    setAreVidsDownloaded(true)
  }

  const callToApi = async(videourl:string, videoIndex:number, timestampData: TimestampObject[]) => {
    console.log(videourl)
    const data = {videourl: videourl, timestampData: timestampData}
    await fetch('http://localhost:3000/api/download',
    {
      method: "POST", 
      body: JSON.stringify(data)
    })
    .then(res => res.json())
    .then((data) => {
      for(let i = 0; i < data.videoData.length; i++){
        const rawData = new Uint8Array(data.videoData[i].video.data)
        // const view = compressIt(rawData)
        console.log(rawData)
        console.log((rawData).toString())
        const view = compress((rawData).toString())
        // console.log(compress(JSON.stringify(rawData)))
        console.log(rawData)
        const downloadedObject = {timestamp: data.videoData[i].timestamp, bufferData: view}
        setDownloadedVids((downloadedVids) => [...downloadedVids, downloadedObject])
        // store.addToDownloadedClips(downloadedObject)
      }
    })
  }

  function compressIt(array){
    // var array = [];
    for (var i = 0; i < 1024; i++) {
        array[array.length] = i % 255;
    }
    var string = String.fromCharCode.apply(null, array);
    var compressed = compress(string);
    var decompressed = decompress(compressed);
    var dearray = [];
    for (var i = 0; i < decompressed.length; i++) {
        dearray[i] = decompressed.charCodeAt(i);
    }
    console.log(array.length, array);
    console.log(string.length, string);
    console.log(compressed.length, compressed);
    console.log(decompressed.length, decompressed);
    console.log(dearray.length, dearray);

  }

  return (
    <ThemeProvider theme={isLight ? lightTheme : darkTheme}>
      <CssBaseline/>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <SettingsMenu/>
          {downloadedVids.length > 1 &&
            <h2>Decide what clips to keep or get rid of</h2>
          }
          {downloadedVids.map(function(vid, key){
            return(
              <CutVideoCard vid={vid} key={key}/>
            )
          })}
          {!areVidsDownloaded &&
            <div style={{display: 'flex', flexDirection: 'column', alignItems: 'center'}}>
              <h1>Loading your selected videos, please wait</h1>
              <RotateRightIcon style={{fontSize: '3rem'}} className="rotate"/>
            </div>
          }
        </main>
        {areVidsDownloaded &&
          <div data-testid="nextpage-btn-container" style={{display: `flex`, justifyContent: 'flex-end', position: 'absolute', right: 70}}>
            <Button href="/editor" variant="contained" className="primary-btn">Next</Button>
          </div>
        }
      </div>
    </ThemeProvider>
  )
}

export default Download
