import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import useStore from '../global/state'
import {useEffect, useState} from 'react'
import { ThemeProvider, CssBaseline, Button } from '@mui/material'
import {darkTheme, lightTheme} from '../styles/themes'
import SettingsMenu from '../components/SettingsMenu'
import PouchDB from 'pouchdb'

const Editor: NextPage = () => {
  const store = useStore();
  const [isLight, setIsLight] = useState(true); //default is darkmode
  const [videos, setVideos] = useState([])

  //run on store.isLight update
  useEffect(() => {
    setIsLight(store.isLight);
  }, [store.isLight]);

  //run once on store.urlList update
  useEffect(() => {
    //logging captions for dev
    // store.urlList.forEach(url => console.log(url.captions))
  }, [store.urlList]);


  function createVideoUrl(buffer:ArrayBuffer){
    return String(URL.createObjectURL(new Blob([buffer], {type: 'video/mp4'})))
  }

  // const vids = useLiveQuery(
  //   () => db.cutVideos.toArray()
  // )
  //
  function getDB(){
    if(process.browser){
      return new PouchDB('cutVids', {auto_compaction: true})
    }
  }
  async function loadNotes(){
    const db = getDB()
    const result = await db?.allDocs({include_docs: true})
    const n = result?.rows.map(row => row.doc)
    setVideos(n)
  }

  useEffect(() => {
    loadNotes()
  }, [])


  return (
    <ThemeProvider theme={isLight ? lightTheme : darkTheme}>
      <CssBaseline/>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <SettingsMenu/>
          <h2 className={styles.title}>Editor</h2>
          {/*vids?.map(function(vid, i){
            return(
              <video key={i} style={{padding: '1rem', width: '100%'}} controls src={createVideoUrl(vid.bufferData)} />
            )
          })*/}
          {videos?.map(function(vid, i){
            return(
              <video key={i} style={{padding: '1rem', width: '100%'}} controls src={createVideoUrl(vid.bufferData)} />
            )

          })}

        </main>
      </div>
    </ThemeProvider>
  )
}

export default Editor
