import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import useStore from '../global/state'
import {useEffect, useState} from 'react'
import { ThemeProvider, CssBaseline, Button } from '@mui/material'
import {darkTheme, lightTheme} from '../styles/themes'
import SettingsMenu from '../components/SettingsMenu'
import TermInputBar from '../components/TermInputBar'
import TermList from '../components/Terms/TermList'

const TermsInput: NextPage = () => {
  const store = useStore();
  const [isLight, setIsLight] = useState(false); //default is darkmode

  //run on store.isLight update
  useEffect(() => {
    setIsLight(store.isLight);
  }, [store.isLight]);

  return (
    <ThemeProvider theme={isLight ? lightTheme : darkTheme}>
      <CssBaseline/>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <div className="main-content-container">
            <SettingsMenu/>
            <h2 className={styles.title}>Words to search for</h2>
            <p>Please input any words you wish to search the captions for, separated by a space if you want to search for multiple</p>
            <div className='input-container'>
              <TermInputBar isLight={isLight}/>
              <div className='button-container'>
              </div>
            </div>
            <TermList/>
          </div>
        </main>
      </div>
    </ThemeProvider>
  )
}

export default TermsInput
